# Site settings
title:          "Danilo Espino"
description:    "despino's blog"
url:            "https://despinouy.github.io"

# Author
author:
  name:         "Danilo Espino"
  url:          "https://despinouy.github.io"
  facebook:     despinoUY
  twitter:      despinoUY
  instagram:    despinoUY
  linkedin:     despinoUY
  github:       despinoUY

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
